version: '3.11'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'media-soft-postgres'
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=2'
      - 'POSTGRES_DB=football'
    volumes:
      - football_db:/var/lib/postgresql/data

  app:
    image: my-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://media-soft-postgres:5432/football
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1
    ports:
      - "8080:8080"
    depends_on:
      - postgres
volumes:
  football_db:


